
package UI;

import DAO.NhanVien_DAO;
import DAO.TaiKhoan_DAO;
import Entity.NhanVien;
import Entity.TaiKhoan;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ThaiHiep
 */
public class DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form DoiMatKhau
     */
    private TaiKhoan_DAO taiKhoan_DAO;
    
    private TaiKhoan tk;
    public DoiMatKhau(TaiKhoan tk) {
        this.tk = tk;
        initComponents();
        taiKhoan_DAO = new TaiKhoan_DAO();
        init();
    }
    
    public void init(){
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        lblAnhMatKhauMoi.setVisible(false);
        lblAnhNhapLaiMatKhau.setVisible(false);
        duLieuMatKhauMoi();
        duLieuNhapLaiMatKhau();
        phimTatChoNutDoiMatKhau();
        DulieuMatKhauCu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDoiMatKhau = new javax.swing.JLabel();
        lblMatKhauCu = new javax.swing.JLabel();
        lblMatKhauMoi = new javax.swing.JLabel();
        lblNhapLaiMatKhau = new javax.swing.JLabel();
        btnDoiMatKhau = new javax.swing.JButton();
        txtMatKhauCu = new javax.swing.JPasswordField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtNhapLaiMatKhau = new javax.swing.JPasswordField();
        lblAnhNhapLaiMatKhau = new javax.swing.JLabel();
        lblAnhMatKhauMoi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        txtDoiMatKhau.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtDoiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDoiMatKhau.setText("Đổi mật khẩu");

        lblMatKhauCu.setText("Mật khẩu cũ");

        lblMatKhauMoi.setText("Mật khẩu mới");

        lblNhapLaiMatKhau.setText("Nhập lại mật khẩu");

        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDoiMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblMatKhauCu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMatKhauMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblNhapLaiMatKhau))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDoiMatKhau)
                                .addGap(0, 145, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMatKhauCu)
                                    .addComponent(txtMatKhauMoi)
                                    .addComponent(txtNhapLaiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblAnhNhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblAnhMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhauCu)
                    .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatKhauMoi)
                            .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNhapLaiMatKhau)
                                .addComponent(txtNhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAnhNhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(btnDoiMatKhau)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAnhMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals("ActionPerformed")) {
              
          }
        try {
            DoiMatKhau();
        } catch (SQLException ex) {
            Logger.getLogger(DoiMatKhau.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed
     private void phimTatChoNutDoiMatKhau(){
        // Tạo phím tắt "Enter" cho JButton
        javax.swing.KeyStroke enterKeyStroke =  javax.swing.KeyStroke.getKeyStroke( java.awt.event.KeyEvent.VK_ENTER, 0);
        
        // Tạo hành động khi phím tắt được nhấn
            javax.swing.Action enterAction = new  javax.swing.AbstractAction("Đổi mật khẩu") {
            
            @Override
            public void actionPerformed( java.awt.event.ActionEvent e) {
                try {
                    DoiMatKhau();
                } catch (SQLException ex) {
                    Logger.getLogger(DoiMatKhau.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        
        // Ánh xạ phím tắt "Enter" với hành động
        InputMap inputMap = btnDoiMatKhau.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap actionMap = btnDoiMatKhau.getActionMap();
        
        inputMap.put(enterKeyStroke, "enterClick");
        actionMap.put("enterClick", enterAction);  
    }
     
    private void DoiMatKhau() throws SQLException{
           
            
        if(taiKhoan_DAO.upDateMatKhau(tk.getTenTK(), txtMatKhauCu.getText(),txtMatKhauMoi.getText())){
            JOptionPane.showMessageDialog(null ,"Đã thay đổi mật khẩu");
            this.dispose();
        }else{
          JOptionPane.showMessageDialog(null ,"Sai mật khẩu cũ");
          lblMatKhauCu.requestFocus();
        }
    }
    
    private void DulieuMatKhauCu(){
        btnDoiMatKhau.setEnabled(false);
        txtMatKhauCu.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                if( !txtMatKhauCu.getText().equals("") && !txtMatKhauMoi.getText().equals("") && !txtNhapLaiMatKhau.getText().equals("")){
                    
                    btnDoiMatKhau.setEnabled(true);
                    
                    
                }else{
                    btnDoiMatKhau.setEnabled(false);
                }
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
               if( !txtMatKhauCu.getText().equals("") && !txtMatKhauMoi.getText().equals("") && !txtNhapLaiMatKhau.getText().equals("")){
                    btnDoiMatKhau.setEnabled(true);    
                }else{
                    btnDoiMatKhau.setEnabled(false);
                }
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                if( !txtMatKhauCu.getText().equals("") && !txtMatKhauMoi.getText().equals("") && !txtNhapLaiMatKhau.getText().equals("")){
                    btnDoiMatKhau.setEnabled(true);
                    
                }else{
                    btnDoiMatKhau.setEnabled(false);
                }
            }
        });
    }
    
    private void duLieuMatKhauMoi(){
        txtMatKhauMoi.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                if( txtMatKhauMoi.getText().length() >= 6){
                            lblAnhMatKhauMoi.setVisible(false);
                             if(!txtNhapLaiMatKhau.getText().equals("")){
                                 if(txtMatKhauMoi.getText().equals(txtNhapLaiMatKhau.getText())){
                                     lblAnhNhapLaiMatKhau.setVisible(true);
                                     lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/dauTich.png")));  
                                     btnDoiMatKhau.setEnabled(false);
                                    if(!txtMatKhauCu.getText().equals("")){
                                        btnDoiMatKhau.setEnabled(true);
                                         
                                    }                                           
                                       
                                }else{
                                        btnDoiMatKhau.setEnabled(false);
                                        lblAnhNhapLaiMatKhau.setVisible(true);
                                        lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                                }     
                             }        
                }else{
                    lblAnhMatKhauMoi.setVisible(true);
                    lblAnhMatKhauMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                    btnDoiMatKhau.setEnabled(false);
                }
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
               if( txtMatKhauMoi.getText().length() >= 6){
                            lblAnhMatKhauMoi.setVisible(false);
                             if(!txtNhapLaiMatKhau.getText().equals("")){
                                 if(txtMatKhauMoi.getText().equals(txtNhapLaiMatKhau.getText())){
                                     lblAnhNhapLaiMatKhau.setVisible(true);
                                     lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/dauTich.png")));  
                                     btnDoiMatKhau.setEnabled(false);
                                    if(!txtMatKhauCu.getText().equals("")){
                                        btnDoiMatKhau.setEnabled(true);     
                                    }                                           
                                }else{
                                        btnDoiMatKhau.setEnabled(false);
                                        lblAnhNhapLaiMatKhau.setVisible(true);
                                        lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                                }     
                             }                            
                                
                }else{
                    if(!txtNhapLaiMatKhau.getText().equals("")){
                        lblAnhMatKhauMoi.setVisible(true);
                        lblAnhMatKhauMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                        lblAnhNhapLaiMatKhau.setVisible(true);
                        lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                        btnDoiMatKhau.setEnabled(false);
                   }else{
                        lblAnhMatKhauMoi.setVisible(true);
                        lblAnhMatKhauMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                        btnDoiMatKhau.setEnabled(false);
                    }
                }
            }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
              if( txtMatKhauMoi.getText().length() >= 6){
                        lblAnhMatKhauMoi.setVisible(false);
                             if(!txtNhapLaiMatKhau.getText().equals("")){
                                 if(txtMatKhauMoi.getText().equals(txtNhapLaiMatKhau.getText())){
                                    if(!txtMatKhauCu.getText().equals("")){
                                        btnDoiMatKhau.setEnabled(true);
                                    }else{
                                        lblAnhNhapLaiMatKhau.setVisible(true);
                                        lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/dauTich.png")));                                        
                                        btnDoiMatKhau.setEnabled(false);   
                                    }
                                }else{
                                        btnDoiMatKhau.setEnabled(false);
                                        lblAnhNhapLaiMatKhau.setVisible(true);
                                        lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                                }     
                             }                                   
                }else{
                    if(!txtNhapLaiMatKhau.getText().equals("")){
                        lblAnhMatKhauMoi.setVisible(true);
                        lblAnhMatKhauMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                        lblAnhNhapLaiMatKhau.setVisible(true);
                        lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                        btnDoiMatKhau.setEnabled(false);
                   }else{
                        lblAnhMatKhauMoi.setVisible(true);
                        lblAnhMatKhauMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                        btnDoiMatKhau.setEnabled(false);
                    }
                }
            }
        });
    }
    
    private void duLieuNhapLaiMatKhau(){
                txtNhapLaiMatKhau.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                if(txtNhapLaiMatKhau.getText().length() >= 6){
                    if( txtNhapLaiMatKhau.getText().equals(txtMatKhauMoi.getText())){
                        btnDoiMatKhau.setEnabled(true);
                        lblAnhNhapLaiMatKhau.setVisible(true);
                        lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/dauTich.png")));
                    }else{
                            lblAnhNhapLaiMatKhau.setVisible(true);
                            lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                            btnDoiMatKhau.setEnabled(false);
                    }
                }else{
                    lblAnhNhapLaiMatKhau.setVisible(true);
                    lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                    btnDoiMatKhau.setEnabled(false);
                    btnDoiMatKhau.setEnabled(false);   
                }
               
            }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                if(txtNhapLaiMatKhau.getText().length() >= 6){
                    if( txtNhapLaiMatKhau.getText().equals(txtMatKhauMoi.getText())){
                        btnDoiMatKhau.setEnabled(true);
                        lblAnhNhapLaiMatKhau.setVisible(true);
                        lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/dauTich.png")));
                    }else{
                            lblAnhNhapLaiMatKhau.setVisible(true);
                            lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                            btnDoiMatKhau.setEnabled(false);
                    }
                }else{
                    lblAnhNhapLaiMatKhau.setVisible(true);
                    lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                    btnDoiMatKhau.setEnabled(false);
                    btnDoiMatKhau.setEnabled(false);   
                }
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                if(txtNhapLaiMatKhau.getText().length() >= 6){
                    if( txtNhapLaiMatKhau.getText().equals(txtMatKhauMoi.getText())){
                        btnDoiMatKhau.setEnabled(true);
                        lblAnhNhapLaiMatKhau.setVisible(true);
                        lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/dauTich.png")));
                    }else{
                            lblAnhNhapLaiMatKhau.setVisible(true);
                            lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                            btnDoiMatKhau.setEnabled(false);
                    }
                }else{
                    lblAnhNhapLaiMatKhau.setVisible(true);
                    lblAnhNhapLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/canhBaoSai.png")));
                    btnDoiMatKhau.setEnabled(false);
                    btnDoiMatKhau.setEnabled(false);   
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnhMatKhauMoi;
    private javax.swing.JLabel lblAnhNhapLaiMatKhau;
    private javax.swing.JLabel lblMatKhauCu;
    private javax.swing.JLabel lblMatKhauMoi;
    private javax.swing.JLabel lblNhapLaiMatKhau;
    private javax.swing.JLabel txtDoiMatKhau;
    private javax.swing.JPasswordField txtMatKhauCu;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtNhapLaiMatKhau;
    // End of variables declaration//GEN-END:variables
}
