

package Pannel;

/**
 *
 * @author FPTSHOP
 */
public class pnlBaoCao extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;


	/** Creates new form pnlBaoCao */
    public pnlBaoCao() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBaoCao = new javax.swing.JLabel();

        lblBaoCao.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblBaoCao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBaoCao.setText("Báo cáo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBaoCao, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 252, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBaoCao;
    // End of variables declaration//GEN-END:variables

}
