
package Pannel;

import DAO.ChiTietHoaDon_DAO;
import DAO.HoaDon_DAO;
import DAO.KhachHang_DAO;
import DAO.NhanVien_DAO;
import DAO.SanPham_DAO;
import DAO_IMP.ChiTietHoaDonDAO_IMP;
import DAO_IMP.HoaDonDAO_IMP;
import DAO_IMP.KhachHangDAO_IMP;
import DAO_IMP.NhanVienDAO_IMP;
import DAO_IMP.SanPhamDAO_IMP;
import entity.ChiTietHoaDon;
import entity.HoaDon;
import entity.KhachHang;
import entity.NhanVien;
import entity.TaiKhoan;
import InHoaDon.FieldHoaDon;
import InHoaDon.ParameterHoaDon;
import InHoaDon.XuLyHoaDon;
import ServiceUser.SelectedDate;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;

import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author FPTSHOP
 */

public class pnlDanhSachHoaDon extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form DanhSachHoaDon
     */
	private static final Gson GSON = new Gson();
    private NhanVien nv;
    private HoaDon_DAO hoaDon_DAO;
    private KhachHang_DAO khachHang_DAO;
    private NhanVien_DAO nhanVien_DAO;
    private ChiTietHoaDon_DAO chiTietHoaDon_DAO;
    public pnlDanhSachHoaDon(TaiKhoan tk,NhanVien nv) {
        this.nv = nv;
        initComponents();
        lblMaNhanVienFont.setText(nv.getMaNV());
        lblTenNhanVienFont.setText(nv.getHoTenNhanVien());
        maHoaDon();
    }
    public void maHoaDon(){
        txtMaHoaDon.getDocument().addDocumentListener(new DocumentListener() {
            
            @Override
            public void insertUpdate(DocumentEvent e) {
               capNhatDanhSachHangCho();
                
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                capNhatDanhSachHangCho();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
    }
    
    public void capNhatDanhSachHangCho(){
        String colTieuDe1[] = new String[]{"Mã hóa đơn", "Mã khách hàng", "Số điện thoại", "Mã nhân viên", "Tên nhân viên", "Ngày lập hóa đơn", "Tổng tiền thanh toán"};
        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);
        
        hoaDon_DAO = new HoaDonDAO_IMP();
                
        LocalDate localNgayLapHoaDon = ngay(data);
                
        HoaDon hoaDon = hoaDon_DAO.layHoaDon( txtMaHoaDon.getText(), localNgayLapHoaDon);
        if(hoaDon.getkhachHang() != null){
            khachHang_DAO = new KhachHangDAO_IMP();
            KhachHang dsKhachHang = khachHang_DAO.layThongTinKhachHang_TheoMaKH(hoaDon.getkhachHang().getMaKhachHang());
            nhanVien_DAO = new NhanVienDAO_IMP();
            NhanVien nhanVien = nhanVien_DAO.layThongTinNhanVien(nv);

                        Object[] row;
                        row = new Object[12];
                        row[0] = hoaDon.getMaHoaDon();
                        row[1] = dsKhachHang.getMaKhachHang();
                        row[2] = dsKhachHang.getSoDienThoai();

                        row[3] = nhanVien.getMaNV();
                        row[4] = nhanVien.getHoTenNhanVien();
                        row[5] = hoaDon.getNgayLap();
                        row[6] = hoaDon.getTongTien();

                        model.addRow(row);

            tblDanhSachHoaDon.setModel(model);
        }else{
            model.setRowCount(0);
             tblDanhSachHoaDon.setModel(model);
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        data = new ServiceUser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMaHoaDon = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        lblNgayLapHoaDon = new javax.swing.JLabel();
        txtNgayHienTai = new javax.swing.JTextField();
        btnChonNgaySinh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblMaKhachHang4 = new javax.swing.JLabel();
        lblTenKhachHang4 = new javax.swing.JLabel();
        lblMaNhanVienFont = new javax.swing.JLabel();
        lblTenNhanVienFont = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachHoaDon = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        data.setTextRefernce(txtNgayHienTai);

        jPanel1.setPreferredSize(new java.awt.Dimension(1325, 787));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm hóa đơn"));
        jPanel2.setPreferredSize(new java.awt.Dimension(528, 400));

        lblMaHoaDon.setText("Mã hóa đơn");

        txtMaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHoaDonActionPerformed(evt);
            }
        });

        lblNgayLapHoaDon.setText("Ngày lập hóa đơn");

        btnChonNgaySinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconAnhLich.png"))); // NOI18N
        btnChonNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonNgaySinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblMaHoaDon)
                .addGap(27, 27, 27)
                .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblNgayLapHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChonNgaySinh)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChonNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaHoaDon)
                        .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNgayLapHoaDon)
                        .addComponent(txtNgayHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách hóa đơn");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhân viên"));
        jPanel5.setPreferredSize(new java.awt.Dimension(528, 400));

        lblMaKhachHang4.setText("Mã nhân viên");

        lblTenKhachHang4.setText("Tên nhân viên");

        lblMaNhanVienFont.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        lblTenNhanVienFont.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTenKhachHang4)
                    .addComponent(lblMaKhachHang4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaNhanVienFont, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenNhanVienFont, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblMaNhanVienFont, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lblMaKhachHang4)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTenKhachHang4)
                    .addComponent(lblTenNhanVienFont, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hóa đơn"));

        tblDanhSachHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã khách hàng", "Số điện thoại", "Mã nhân viên", "Tên nhân viên", "Ngày lập hóa đơn", "Tổng tiền thanh toán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachHoaDon);

        jButton1.setText("Làm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xuất hóa đơn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 
     private LocalDate parseDate(String inputDate) {
    String[] parts = inputDate.split("-"); // Tách chuỗi thành mảng các phần tử

    if (parts.length == 3) { // Kiểm tra có đủ phần tử ngày, tháng, năm không
        int day = Integer.parseInt(parts[0]);
        int month = Integer.parseInt(parts[1]);
        int year = Integer.parseInt(parts[2]);

        // Kiểm tra và xử lý ngày, tháng, năm nếu cần
        // Ví dụ: nếu các thành phần không thỏa mãn điều kiện ngày, tháng, năm hợp lệ

        return LocalDate.of(year, month, day); // Tạo đối tượng LocalDate
    } else {
        // Xử lý khi chuỗi không đúng định dạng
        return null; // hoặc throw exception tùy thuộc vào cách xử lý của bạn
    }
}
private LocalDate ngay(ServiceUser.DateChooser dateTextField){
    SelectedDate selectedNgayKetThuc = dateTextField.getSelectedDate();
    String inputDate = selectedNgayKetThuc.getDay() + "-" + selectedNgayKetThuc.getMonth() + "-" + selectedNgayKetThuc.getYear();
    LocalDate ngay = parseDate(inputDate);
    return ngay;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHoaDonActionPerformed

    private void btnChonNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonNgaySinhActionPerformed
        // TODO add your handling code here:
        data.showPopup();
    }//GEN-LAST:event_btnChonNgaySinhActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            int row = tblDanhSachHoaDon.getSelectedRow();
           
                inHoaDon() ;
            
            
        } catch (JRException ex) {
            Logger.getLogger(pnlDanhSachHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblDanhSachHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachHoaDonMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_tblDanhSachHoaDonMouseClicked
    public void inHoaDon() throws JRException {
        int row = tblDanhSachHoaDon.getSelectedRow();
        if(row!=-1){
             XuLyHoaDon.getInstance().compileReport();
         try {
                    List<FieldHoaDon> fields = new ArrayList<>();
                    chiTietHoaDon_DAO = new ChiTietHoaDonDAO_IMP();
                    ArrayList<ChiTietHoaDon> dsChiTietHoaDon = chiTietHoaDon_DAO.layDanhSachCTHoaDonTheoMa(txtMaHoaDon.getText());
                    for (ChiTietHoaDon chiTietHoaDon : dsChiTietHoaDon) {
                    	SanPham_DAO sanPham_DAO = new SanPhamDAO_IMP();
                    	
                    	String json = GSON.toJson(sanPham_DAO.layDanhSachTheoMaSach(chiTietHoaDon.getSanPham().getMaSanPham())+"");
        		        JsonArray jsonArray = GSON.fromJson(json, JsonArray.class);
        		        String tenSanPham = "";
        		        for (JsonElement jsonElement : jsonArray) {
        				
//        					System.out.println("Tên sản phẩm : "+jsonElement.getAsJsonObject());
        		        	tenSanPham = jsonElement.getAsJsonObject().get("tenSanPham").getAsString();
        					
        					
//        					int soLuongTon1 = jsonElement.getAsJsonObject().get("soLuongTon").getAsInt();
//        					System.out.println("Số lượng tồn: "+soLuongTon1);
        					
        		        }
                    	
//                        sach_DAO = new SachDAO_IMP();
//                        String tenSanPham = "";
//                        ArrayList<Sach> dsSach = sach_DAO.layDanhSachTheoMaSach(chiTietHoaDon.getSanPham().getMaSanPham());
//                        for (Sach sach : dsSach) {
//                            tenSanPham = sach.getTenSanPham();
//                        }
//                        vanPhongPham_DAO = new VanPhongPhamDAO_IMP();
//                        
//                        ArrayList<VanPhongPham> dsVanPhongPham = vanPhongPham_DAO.layDanhSanPhamVanPhongPham_TheoMa(chiTietHoaDon.getSanPham().getMaSanPham());
//                        for (VanPhongPham vanPhongPham : dsVanPhongPham) {
//                            tenSanPham = vanPhongPham.getTenSanPham();
//                        }
                        
                       
                        Object soLuongObj = chiTietHoaDon.getSoLuong();
                      
                        int soLuong = Integer.parseInt(soLuongObj+"");

                        // Kiểm tra và chuyển đổi kiểu dữ liệu cho giaBan
                        Object giaBanObj = chiTietHoaDon.getDonGia();

                            System.out.println(giaBanObj+" ");
                        double giaBan = Double.parseDouble(giaBanObj+"");

                        // Kiểm tra và chuyển đổi kiểu dữ liệu cho soLuong

                        // Kiểm tra và chuyển đổi kiểu dữ liệu cho tongTienSP
                        
                        Object tongTienSPObj = soLuong * giaBan;
                        System.out.println(tongTienSPObj+" ");
                        double tongTienSP = Double.parseDouble(tongTienSPObj+"");

                         fields.add(new FieldHoaDon(tenSanPham, soLuong, giaBan, tongTienSP));
                         
                    }    
                hoaDon_DAO = new HoaDonDAO_IMP();
                LocalDate localNgayLapHoaDon = ngay(data);
                
                HoaDon hoaDon = hoaDon_DAO.layHoaDon( txtMaHoaDon.getText(), localNgayLapHoaDon);
                
                nhanVien_DAO = new NhanVienDAO_IMP();
                
                NhanVien nhanVien = nhanVien_DAO.layThongTinNhanVien(nv);
                
                String tenNhanVien = nhanVien.getHoTenNhanVien();
                
                String maHoaDon = txtMaHoaDon.getText();
                
                String tienThanhToan = hoaDon.getTongTien()+"";
                
                LocalDate ngay = LocalDate.now();
                
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                
                String ngayTao = ngay.format(formatter);
                
                khachHang_DAO = new KhachHangDAO_IMP();
                
               String stringkh =  hoaDon.getkhachHang().getMaKhachHang();
               String inputKh = stringkh.substring(0, 3);
               String sdt = "Khách hàng lẻ";
                if(inputKh.equals("KHL")){
                      sdt = "";  
                }else{
                    KhachHang khachHang = khachHang_DAO.layThongTinKhachHang_TheoMaKH(hoaDon.getkhachHang().getMaKhachHang());
                    sdt = khachHang.getSoDienThoai();
                }
                String tienBD = hoaDon.getTienBanDau()+"";
                String khachDua = hoaDon.getSoTienKhachDua()+"";
                if(khachDua.length()!=0){
                    khachDua = hoaDon.getSoTienKhachDua() +"VND";
                }else{
                    khachDua = tienBD + " VND";
                }
                String khuyenMai = "";
                if (khuyenMai.equals("")){
                    khuyenMai = "0 VND";
                }else{
                    
                }
                String traKhach = hoaDon.getTienThua()+" VND";
                if(khachDua.equals("")){
                    traKhach = "0 VND";
                }else{
                   
                }
                   ParameterHoaDon dataprint = new ParameterHoaDon(tenNhanVien, maHoaDon, tienThanhToan, ngayTao, sdt, tienBD, khuyenMai, khachDua, traKhach, fields);
                XuLyHoaDon.getInstance().printReportPayment(dataprint);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
       
        }
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonNgaySinh;
    private ServiceUser.DateChooser data;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaKhachHang4;
    private javax.swing.JLabel lblMaNhanVienFont;
    private javax.swing.JLabel lblNgayLapHoaDon;
    private javax.swing.JLabel lblTenKhachHang4;
    private javax.swing.JLabel lblTenNhanVienFont;
    private javax.swing.JTable tblDanhSachHoaDon;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtNgayHienTai;
    // End of variables declaration//GEN-END:variables
}
