
package Pannel;

import DAO.Thue_DAO;
import DAO.QuyDinh_DAO;
import DAO.TheLoai_DAO;
import DAO.XuatXu_DAO;
import Entity.QuyDinh;
import Entity.Thue;
import Entity.TheLoai;
import Entity.XuatXu;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author FPTSHOP
 */
public class pnlQuyDinh extends javax.swing.JPanel {

    private TheLoai_DAO theLoai_DAO;
    private XuatXu_DAO xuatXu_DAO;
    private QuyDinh_DAO quyDinh_DAO;
    private int soLuongToiThieu, soLuongToiDa;
    private float VAT;
    private Thue_DAO thue_DAO;

    /**
     * Creates new form pnlQuyDinh
     */
    public pnlQuyDinh() {
        initComponents();
        init();
    }
    public void init(){
        theLoai_DAO = new TheLoai_DAO();
        ArrayList<TheLoai> dstl =  theLoai_DAO.layDanhSachTheLoai();
        for (TheLoai theLoai : dstl) {
            cboTheLoai.addItem(theLoai.getTenTheLoai());
        }
        xuatXu_DAO = new XuatXu_DAO();
        ArrayList<XuatXu> dsxx = xuatXu_DAO.layDanhSachXuatXu();
        for (XuatXu xuatXu : dsxx) {
            cboXuatXu.addItem(xuatXu.getTenQuocGia());
        }
      //  addDataComboNgonNgu(cboNgonNgu);
        
        quyDinh_DAO = new QuyDinh_DAO();
        QuyDinh quyDinh = quyDinh_DAO.layDuLieuQuyDinh();
        if(quyDinh == null){
            txtSoLuongToiThieu.setText("0");
            txtSoLuongToiDa.setText("0");
            txtVAT.setText("0.0 %"); 
        }else{
        txtSoLuongToiDa.setText(quyDinh.getSoLuongToiDa()+"");
        txtSoLuongToiThieu.setText(quyDinh.getSoLuongToiThieu()+"");
        txtVAT.setText(quyDinh.getVAT() + " %");
        }
        
        
       
        
       
    }
    
     private void addDataComboNgonNgu(JComboBox cbo){
         cbo.setModel(new DefaultComboBoxModel<>(
            new String[]{
            "Tiếng Việt",
            "Tiếng Anh",
            "Tiếng Trung",
            "Tiếng Đức",
            "Tiếng Tây Ban Nha",
            "Tiếng Nhật",
            "Tiếng Nga"
            }
         ));
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cboTheLoai = new javax.swing.JComboBox<>();
        txtTheLoai = new javax.swing.JTextField();
        lblTheLoai = new javax.swing.JLabel();
        btnApDung1 = new javax.swing.JButton();
        btnMacDinh1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cboXuatXu = new javax.swing.JComboBox<>();
        txtXuatXu = new javax.swing.JTextField();
        lblXuatXu = new javax.swing.JLabel();
        btnApDung2 = new javax.swing.JButton();
        btnMacDinh2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuongToiThieu = new javax.swing.JTextField();
        txtSoLuongToiDa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVAT = new javax.swing.JTextField();
        btnApDung = new javax.swing.JButton();
        btnMacDinh = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quy định");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thuế"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sách"));

        cboTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTheLoaiActionPerformed(evt);
            }
        });

        txtTheLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTheLoaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTheLoaiFocusLost(evt);
            }
        });
        txtTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTheLoaiActionPerformed(evt);
            }
        });

        lblTheLoai.setText("Thể loại");

        btnApDung1.setText("Áp dụng");
        btnApDung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApDung1ActionPerformed(evt);
            }
        });

        btnMacDinh1.setText("Mặc định");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTheLoai)
                .addGap(46, 46, 46)
                .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnApDung1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnMacDinh1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTheLoai)
                    .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApDung1)
                    .addComponent(btnMacDinh1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Văn phòng phẩm"));

        cboXuatXu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboXuatXuActionPerformed(evt);
            }
        });

        txtXuatXu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtXuatXuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtXuatXuFocusLost(evt);
            }
        });

        lblXuatXu.setText("Xuất xứ");

        btnApDung2.setText("Áp dụng");
        btnApDung2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApDung2ActionPerformed(evt);
            }
        });

        btnMacDinh2.setText("Mặc định");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblXuatXu)
                .addGap(32, 32, 32)
                .addComponent(cboXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnApDung2)
                .addGap(43, 43, 43)
                .addComponent(btnMacDinh2)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXuatXu)
                    .addComponent(cboXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApDung2)
                    .addComponent(btnMacDinh2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Số lượng tồn"));

        jLabel2.setText("Số lượng nhập tối thiểu");

        jLabel3.setText("Số lượng nhập tối đa");

        jLabel4.setText("VAT");

        txtVAT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVATFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVATFocusLost(evt);
            }
        });
        txtVAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVATActionPerformed(evt);
            }
        });

        btnApDung.setText("Áp dụng");
        btnApDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApDungActionPerformed(evt);
            }
        });

        btnMacDinh.setText("Mặc định");
        btnMacDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMacDinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSoLuongToiThieu, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(txtSoLuongToiDa)
                    .addComponent(txtVAT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMacDinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnApDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(209, 209, 209))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSoLuongToiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoLuongToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApDung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMacDinh))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTheLoaiActionPerformed
        // TODO add your handling code here:
        thue_DAO  = new Thue_DAO();
        ArrayList<Thue> quyDinh =  thue_DAO.layDuLieuThue();
        for (Thue quyDinhThueTheLoai : quyDinh) {
            System.out.println(quyDinhThueTheLoai.getThue());
        }
        theLoai_DAO = new TheLoai_DAO();
        ArrayList<TheLoai> dsTheLoai = theLoai_DAO.layDanhSachTheLoai();
      
        System.out.println(cboTheLoai.getSelectedItem());
        for (TheLoai theLoai : dsTheLoai) {
            if(cboTheLoai.getSelectedItem().equals(theLoai.getTenTheLoai())){
                for (Thue quyDinhThueTheLoai : quyDinh) {
                    if(theLoai.getMaTheLoai().equals(quyDinhThueTheLoai.getId())){
                        txtTheLoai.setText(quyDinhThueTheLoai.getThue() + " %"); 
                        break;
                    }else{
                        System.out.println("Pannel.pnlQuyDinh.cboTheLoaiActionPerformed()");
                        txtTheLoai.setText("0.0 %");
                    }
                }
            }
        }
    }//GEN-LAST:event_cboTheLoaiActionPerformed

    private void cboXuatXuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboXuatXuActionPerformed
        // TODO add your handling code here:
        thue_DAO  = new Thue_DAO();
        ArrayList<Thue> quyDinh =  thue_DAO.layDuLieuThue();
        for (Thue quyDinhThueTheLoai : quyDinh) {
            System.out.println(quyDinhThueTheLoai.getThue());
        }
        theLoai_DAO = new TheLoai_DAO();
      
         ArrayList<XuatXu> dsXuatXu = xuatXu_DAO.layDanhSachXuatXu();
            
        System.out.println(cboTheLoai.getSelectedItem());
       for (XuatXu xuatXu : dsXuatXu) {
            if(cboXuatXu.getSelectedItem().equals(xuatXu.getTenQuocGia())){
                for (Thue quyDinhThueTheLoai : quyDinh) {
                    if(xuatXu.getMaXuatXu().equals(quyDinhThueTheLoai.getId())){
                        txtXuatXu.setText(quyDinhThueTheLoai.getThue() + " %"); 
                        break;
                    }else{
                        System.out.println("Pannel.pnlQuyDinh.cboTheLoaiActionPerformed()");
                        txtXuatXu.setText("0.0 %");
                    }
                }
            }
        }
    }//GEN-LAST:event_cboXuatXuActionPerformed

    private void txtVATFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVATFocusGained
        // TODO add your handling code here:
        String priceWithoutCurrency = txtVAT.getText().replaceAll("[^\\d.]+", "");
        double parsedNumber = Double.parseDouble(priceWithoutCurrency);
        
        txtVAT.setText( parsedNumber+"");
    }//GEN-LAST:event_txtVATFocusGained

    private void txtVATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVATActionPerformed

    private void txtVATFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVATFocusLost
        // TODO add your handling code here:
        txtVAT.setText(txtVAT.getText()+" %");
    }//GEN-LAST:event_txtVATFocusLost

    private void txtTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTheLoaiActionPerformed

    private void btnApDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApDungActionPerformed
        // TODO add your handling code here:
        
        quyDinh_DAO = new QuyDinh_DAO();
        soLuongToiThieu = Integer.parseInt(txtSoLuongToiThieu.getText());
        soLuongToiDa = Integer.parseInt(txtSoLuongToiDa.getText());
        String priceWithoutCurrency = txtVAT.getText().replaceAll("[^\\d.]+", "");
        double parsedNumber = Double.parseDouble(priceWithoutCurrency);
        VAT = (float)parsedNumber;
        QuyDinh quyDinh = new QuyDinh(soLuongToiThieu, soLuongToiDa, VAT);
        if(quyDinh_DAO.layDuLieuQuyDinh()!=null){
            quyDinh_DAO.updateQuyDinh( quyDinh);
        }else{
            System.out.println("2");
            System.out.println(soLuongToiThieu);
            System.out.println(soLuongToiDa);
            System.out.println(VAT);
            quyDinh_DAO.InsertQuyDinh(soLuongToiThieu, soLuongToiDa, VAT);
        }
    }//GEN-LAST:event_btnApDungActionPerformed

    private void btnMacDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMacDinhActionPerformed
        // TODO add your handling code here:
         txtSoLuongToiThieu.setText("0");
            txtSoLuongToiDa.setText("0");
            txtVAT.setText("0.0 %"); 
    }//GEN-LAST:event_btnMacDinhActionPerformed

    private void btnApDung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApDung1ActionPerformed
        // TODO add your handling code here:
        thue_DAO  = new Thue_DAO();
        ArrayList<Thue> quyDinh =  thue_DAO.layDuLieuThue();
        theLoai_DAO = new TheLoai_DAO();
        ArrayList<TheLoai> dsTheLoai = theLoai_DAO.layDanhSachTheLoai();
        int dem = 0;
        String ma = "";
            for (TheLoai theLoai : dsTheLoai) {
                if(cboTheLoai.getSelectedItem().equals(theLoai.getTenTheLoai())){
                    ma = theLoai.getMaTheLoai();
                    for (Thue thue : quyDinh) {
                        if(theLoai.getMaTheLoai().equals(thue.getId())){
                                String priceWithoutCurrency = txtTheLoai.getText().replaceAll("[^\\d.]+", "");
                                double parsedNumber = Double.parseDouble(priceWithoutCurrency);
                                Thue QuyDinhTheLoai = new Thue(theLoai.getMaTheLoai(), (float)parsedNumber);
                                thue_DAO.updateThue(QuyDinhTheLoai);
                                dem++;
                                break;
                        }
                   }
            }
        }
            if(dem==0){
                String priceWithoutCurrency = txtTheLoai.getText().replaceAll("[^\\d.]+", "");
                double parsedNumber = Double.parseDouble(priceWithoutCurrency);
                Thue QuyDinhTheLoai = new Thue(ma, (float)parsedNumber);
                thue_DAO.insertThue(QuyDinhTheLoai);
                        
            }
    }//GEN-LAST:event_btnApDung1ActionPerformed

    private void txtTheLoaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTheLoaiFocusGained
        // TODO add your handling code here:
        String priceWithoutCurrency = txtTheLoai.getText().replaceAll("[^\\d.]+", "");
        double parsedNumber = Double.parseDouble(priceWithoutCurrency);
        txtTheLoai.setText( parsedNumber+"");
    }//GEN-LAST:event_txtTheLoaiFocusGained

    private void txtTheLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTheLoaiFocusLost
        // TODO add your handling code here:
         txtTheLoai.setText(txtTheLoai.getText()+" %");
    }//GEN-LAST:event_txtTheLoaiFocusLost

    private void btnApDung2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApDung2ActionPerformed
        // TODO add your handling code here:
        thue_DAO  = new Thue_DAO();
        ArrayList<Thue> quyDinh =  thue_DAO.layDuLieuThue();
        xuatXu_DAO = new XuatXu_DAO();
        ArrayList<XuatXu> dsXuatXu = xuatXu_DAO.layDanhSachXuatXu();
        int dem = 0;
        String ma = "";
        
        for (XuatXu xuatXu: dsXuatXu) {
                if(cboXuatXu.getSelectedItem().equals(xuatXu.getTenQuocGia())){
                    ma = xuatXu.getMaXuatXu();
                    for (Thue thue : quyDinh) {
                        if(xuatXu.getMaXuatXu().equals(thue.getId())){
                            String priceWithoutCurrency = txtXuatXu.getText().replaceAll("[^\\d.]+", "");
                            double parsedNumber = Double.parseDouble(priceWithoutCurrency);
                            Thue QuyDinhTheLoai = new Thue(xuatXu.getMaXuatXu(), (float)parsedNumber);
                            thue_DAO.updateThue(QuyDinhTheLoai);
                            dem++;
                            break;
                    }
                }
            }
        }
        if(dem==0){
             String priceWithoutCurrency = txtXuatXu.getText().replaceAll("[^\\d.]+", "");
                        double parsedNumber = Double.parseDouble(priceWithoutCurrency);
                        Thue QuyDinhTheLoai = new Thue(ma, (float)parsedNumber);
                        thue_DAO.insertThue(QuyDinhTheLoai);
                   
        }
    }//GEN-LAST:event_btnApDung2ActionPerformed

    private void txtXuatXuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtXuatXuFocusGained
        // TODO add your handling code here:
         String priceWithoutCurrency = txtXuatXu.getText().replaceAll("[^\\d.]+", "");
        double parsedNumber = Double.parseDouble(priceWithoutCurrency);
        
        txtXuatXu.setText( parsedNumber+"");
    }//GEN-LAST:event_txtXuatXuFocusGained

    private void txtXuatXuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtXuatXuFocusLost
        // TODO add your handling code here:
        txtXuatXu.setText(txtXuatXu.getText()+" %");
    }//GEN-LAST:event_txtXuatXuFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApDung;
    private javax.swing.JButton btnApDung1;
    private javax.swing.JButton btnApDung2;
    private javax.swing.JButton btnMacDinh;
    private javax.swing.JButton btnMacDinh1;
    private javax.swing.JButton btnMacDinh2;
    private javax.swing.JComboBox<String> cboTheLoai;
    private javax.swing.JComboBox<String> cboXuatXu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblTheLoai;
    private javax.swing.JLabel lblXuatXu;
    private javax.swing.JTextField txtSoLuongToiDa;
    private javax.swing.JTextField txtSoLuongToiThieu;
    private javax.swing.JTextField txtTheLoai;
    private javax.swing.JTextField txtVAT;
    private javax.swing.JTextField txtXuatXu;
    // End of variables declaration//GEN-END:variables
}
