
package Pannel;

import DAO.KhachHang_DAO;
import DAO_IMP.KhachHangDAO_IMP;
import entity.KhachHang;
import entity.TaiKhoan;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author NTH
 */
public class pnlTraCuuKhachHang extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form TraCuuKhachHang
     */
    private String tp = "Tỉnh/Thành phố";
    private String q = "Quận/huyện";
    private String cboDiaChi = "";
    private ArrayList<String> cities ;
    private ArrayList<String> districts ;
    private ArrayList<String> wardsDistricts ;
    private TaiKhoan tk;
    private KhachHang_DAO khachHang_DAO;
    public pnlTraCuuKhachHang(TaiKhoan tk) throws IOException {
        initComponents();
        addPlaceholderStyle(txtTimKiem);
        Timer timeXuatHienDiaChi = new Timer(500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                    
                try {
                    cities = readExcel_City();
                        for (String city : cities) {
                            cboTinhThanhPho.addItem(city);
                        }
                } catch (IOException ex) {
                    Logger.getLogger(pnlTraCuuNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            }
        });
        
        timeXuatHienDiaChi.setRepeats(false); // Chỉ chạy một lần
        timeXuatHienDiaChi.start();
          
          khachHang_DAO = new KhachHangDAO_IMP();
       capNhatDanhSachKhachHangTheoSoDienThoai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblMaKhachHang = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblTenKhachHang = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        cboQuanHuyen = new javax.swing.JComboBox<>();
        cboTinhThanhPho = new javax.swing.JComboBox<>();
        cboPhuongXa = new javax.swing.JComboBox<>();
        btnLamMoi = new javax.swing.JButton();
        btnThemKhachHang = new javax.swing.JButton();
        btnSuaThongTinKhachHang = new javax.swing.JButton();
        btnLapHoaDon = new javax.swing.JButton();
        lblMaKHKyTu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblTimKiem = new javax.swing.JLabel();
        txtTimKiem = new ServiceUser.TextFieldSuggestion();
        txtTraCuuKhachHang = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12)))); // NOI18N

        lblMaKhachHang.setText("Mã khách hàng        ");

        lblSoDienThoai.setText("Số điện thoại");

        lblDiaChi.setText("Địa chỉ");

        lblTenKhachHang.setBackground(new java.awt.Color(0, 0, 0));
        lblTenKhachHang.setText("Tên khách hàng");

        txtTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachHangActionPerformed(evt);
            }
        });

        cboQuanHuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboQuanHuyenActionPerformed(evt);
            }
        });

        cboTinhThanhPho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTinhThanhPhoActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThemKhachHang.setText("Thêm khách hàng");
        btnThemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKhachHangActionPerformed(evt);
            }
        });

        btnSuaThongTinKhachHang.setText("Sửa thông tin khách hàng");

        btnLapHoaDon.setText("Lập hóa đơn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnLapHoaDon)
                .addGap(34, 34, 34)
                .addComponent(btnThemKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnSuaThongTinKhachHang)
                .addGap(228, 228, 228))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMaKhachHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMaKHKyTu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txtTenKhachHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(cboTinhThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(cboQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaKHKyTu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenKhachHang)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSoDienThoai)
                        .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiaChi)
                    .addComponent(cboTinhThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLamMoi)
                    .addComponent(btnLapHoaDon)
                    .addComponent(btnThemKhachHang)
                    .addComponent(btnSuaThongTinKhachHang))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Địa chỉ"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        lblTimKiem.setText("Tìm kiếm");

        txtTimKiem.setText("Tìm kiếm theo số điện thoại");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusLost(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimKiem))
                .addContainerGap())
        );

        txtTraCuuKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTraCuuKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTraCuuKhachHang.setText("Tra cứu khách hàng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTraCuuKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtTraCuuKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachHangActionPerformed

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        // TODO add your handling code here:
        if(txtTimKiem.getText().equals("Tìm kiếm theo số điện thoại")){
            txtTimKiem.setText("");
            removePlaceholderStyle(txtTimKiem);
        }
    }//GEN-LAST:event_txtTimKiemFocusGained
    public void addPlaceholderStyle(JTextField textFile){
        Font  font = textFile.getFont();
        font = font.deriveFont(Font.ITALIC);
        textFile.setFont(font);
        textFile.setForeground(Color.black);
    }
    public void removePlaceholderStyle(JTextField textFile){
         Font  font = textFile.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textFile.setFont(font);
        textFile.setForeground(Color.black);
    }
    private void txtTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusLost
        // TODO add your handling code here:
        if(txtTimKiem.getText().length()==0){
            addPlaceholderStyle(txtTimKiem);
            txtTimKiem.setText("Tìm kiếm theo số điện thoại");
        }
    }//GEN-LAST:event_txtTimKiemFocusLost

    private void btnThemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemKhachHangActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        //txtMaKhachHang.setText("");
       // txtMaKhachHang.setEditable(true);
        txtSoDienThoai.setText("");
        txtTenKhachHang.setText("");
        cboTinhThanhPho.setSelectedItem("Tỉnh/Thành phố");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void cboQuanHuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboQuanHuyenActionPerformed
        // TODO add your handling code here:
//        String t = cboQuanHuyen.getSelectedItem()+"";

        cboQuanHuyen.addItem(q);
        // System.out.println(districtComboBox.getSelectedItem()+"");
        if( q == "Tỉnh/Thành phố"){

            //wardComboBox.removeAllItems();
            //wardComboBox.addItem("Phường/xã");
            // wardComboBox.setEnabled(true);
            // updateWardComboBox();
            // q = districtComboBox.getSelectedItem()+"";
            cboPhuongXa.setEnabled(false);
            cboPhuongXa.removeAllItems();
            cboPhuongXa.addItem("Phường/xã");

        }else{
            cboPhuongXa.setEnabled(true);
            try {
                wardsDistricts = readExcel_wardsDistrict(cboQuanHuyen,cboPhuongXa);
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
            if(!cboDiaChi.equals(cboQuanHuyen.getSelectedItem())){
                cboPhuongXa.removeAllItems();
                cboPhuongXa.addItem("Phường/xã");
                for (String wad : wardsDistricts) {
                    cboPhuongXa.addItem(wad);
                }
            }
        }
        
        cboDiaChi = cboQuanHuyen.getSelectedItem()+"";
        cboQuanHuyen.removeItem(q);

    }//GEN-LAST:event_cboQuanHuyenActionPerformed

    private void cboTinhThanhPhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTinhThanhPhoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(!tp.equals(cboTinhThanhPho.getSelectedItem()+"")||cboTinhThanhPho.getSelectedItem().equals("Tỉnh/Thành phố")){
            q = cboTinhThanhPho.getSelectedItem()+"";
            //System.out.println(provinceComboBox.getSelectedItem());
            if(cboTinhThanhPho.getSelectedItem().equals("Tỉnh/Thành phố")){

                cboQuanHuyen.removeAllItems();
                cboQuanHuyen.addItem("Quận/huyện");
                cboPhuongXa.removeAllItems();
                cboPhuongXa.addItem("Phường/xã");
                cboQuanHuyen.setEnabled(false);
                cboPhuongXa.setEnabled(false);

                System.out.println("1223 "+"Tỉnh/Thành phố");
            }else{

                try {
                    districts = readExcel_districts(cboTinhThanhPho,cboQuanHuyen,cboPhuongXa,tp);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
                cboQuanHuyen.removeAllItems();
                cboQuanHuyen.addItem("Quận/huyện");
                for (String district : districts) {
                    cboQuanHuyen.addItem(district);
                }
                cboPhuongXa.setEnabled(true);
                try {
                    wardsDistricts = readExcel_wardsDistrict(cboQuanHuyen,cboPhuongXa);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
                cboPhuongXa.removeAllItems();
                cboPhuongXa.addItem("Phường/xã");
                for (String wad : wardsDistricts) {
                    cboPhuongXa.addItem(wad);
                }
            }
        }
        tp = cboTinhThanhPho.getSelectedItem()+"";
    }//GEN-LAST:event_cboTinhThanhPhoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        lblMaKHKyTu.setText(jTable1.getValueAt(row, 0).toString());
        txtTenKhachHang.setText(jTable1.getValueAt(row, 1).toString());
        txtSoDienThoai.setText(jTable1.getValueAt(row, 2).toString());
        khachHang_DAO = new KhachHangDAO_IMP();
              if(jTable1.getValueAt(row, 3).toString().equals("")){
                    cboTinhThanhPho.setSelectedItem("Tỉnh/Thành phố");
                }else{
                    	
		    String part1 = "";
                    String part2 = "";
                    String part3 = "";
                    String input = jTable1.getValueAt(row, 3).toString();
                    String[] parts = input.split("-");	
                    for (int i = 0; i < parts.length; i++) {
                        switch (i) {
                            case 0 -> part1 = parts[i];
                            case 1 -> part2 = parts[i];
                            default -> part3 =parts[i];
                        }
			}
                    cboTinhThanhPho.setSelectedItem(part1);
                   
                    if(!part2.equals("")){
                        cboQuanHuyen.setSelectedItem(part2);
                         if(!part3.equals("")){
                            cboPhuongXa.setSelectedItem(part3);
                        }
                    
                            
                }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed
		public static ArrayList<String> readExcel_City() throws IOException {
		//Đọc dữ liệu từ file Diachi.xlsx
                ArrayList<String> cities = new ArrayList<>();
        //Nạp file input stream đưa về dạng excel
        try (FileInputStream file = new FileInputStream("src\\Li\\Book1.xlsx"); //Nạp file input stream đưa về dạng excel
                XSSFWorkbook wb = new XSSFWorkbook(file)) {
            //Đọc file từ Sheet 1 (bắt đầu từ số 0)
            XSSFSheet sheet = wb.getSheetAt(0);
            //Lấy các giá trị trong các cột
          
            int v = 0;
            for(Row row:sheet) {
                if(!cities.contains(row.getCell(0)+"")) {
                    if(row.getCell(0) !=null ) {
                        cities.add(row.getCell(0)+"");
                        v++;
                    }
                }
            }
            System.out.println(v);
        }
		return cities;
}   
    public static ArrayList<String> readExcel_districts(JComboBox<String> cbo,JComboBox<String> cbo1,JComboBox<String> cbo2,String tb) throws IOException {
	//Đọc dữ liệu từ file Diachi.xlsx
            ArrayList<String> districts = new ArrayList<>();
        //Nạp file input stream đưa về dạng excel
        try (FileInputStream file = new FileInputStream("src\\Li\\Book1.xlsx"); //Nạp file input stream đưa về dạng excel
                XSSFWorkbook wb = new XSSFWorkbook(file)) {
            //Đọc file từ Sheet 1 (bắt đầu từ số 0)
            XSSFSheet sheet = wb.getSheetAt(0);
            //Lấy các giá trị trong các cột
           
            //Duyệt các row
            
            int v = 0;
            if(cbo.getSelectedItem().equals("Tỉnh/Thành phố")){
                cbo1.setEnabled(false);
                cbo2.setEnabled(false);
            }else{
                cbo1.setEnabled(true);
                cbo1.setEditable(false);
                cbo2.setEnabled(true);
            }
            for(Row row:sheet) {
                if(row.getCell(0) != null && cbo.getSelectedItem().equals(row.getCell(0)+"") ) {
                    if(!districts.contains(row.getCell(2)+"" )) {
                        districts.add(row.getCell(2)+"");
                        v++;
                    }
                }
            }
            
            System.out.println(v);
        }
		return districts;
	}    
     public static ArrayList<String> readExcel_wardsDistrict(JComboBox<String> cbo,JComboBox<String> cbo1) throws IOException {
		//Đọc dữ liệu từ file Diachi.xlsx
    	 ArrayList<String> wardsDistrict = new ArrayList<>();
        //Nạp file input stream đưa về dạng excel
        try (FileInputStream file = new FileInputStream("src\\Li\\Book1.xlsx"); //Nạp file input stream đưa về dạng excel
                XSSFWorkbook wb = new XSSFWorkbook(file)) {
            //Đọc file từ Sheet 1 (bắt đầu từ số 0)
            XSSFSheet sheet = wb.getSheetAt(0);
            //Lấy các giá trị trong các cột
//            FormulaEvaluator formula = wb.getCreationHelper().createFormulaEvaluator();
            //Duyệt các row
            int v = 0;
            
            if(cbo.getSelectedItem().equals("Quận/huyện")){
                cbo1.setEnabled(false);
            }else{   
                cbo.setEnabled(true);
            }
            for(Row row:sheet) {
                if(row.getCell(2) != null && cbo.getSelectedItem().equals(row.getCell(2)+"") ) {
                    if(!wardsDistrict.contains(row.getCell(4)+"" )) {
                        wardsDistrict.add(row.getCell(4)+"");
                        
                    }
                }
            }
            System.out.println(v);
        }
		return wardsDistrict;
	}
     
     public void capNhatDanhSachKhachHangTheoSoDienThoai(){
        khachHang_DAO = new KhachHangDAO_IMP();
        String timKiem = txtTimKiem.getText();
        if(!timKiem.equals("Tìm kiếm theo số điện thoại")){
            txtTimKiem.getDocument().addDocumentListener(new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                  
                       KhachHang khachHang = khachHang_DAO.layThongTinKhachHang(txtTimKiem.getText());
                       String colTieuDe1[] = new String[]{"Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Địa chỉ"};
                        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);
                           Object[] row;
                            row = new Object[4];
                            row[0] = khachHang.getMaKhachHang();
                            row[1] = khachHang.getTenKhachHang();
                            row[2] = khachHang.getSoDienThoai();
                            row[3] = khachHang.getDiaChi();
                           model.addRow(row);
           
           jTable1.setModel(model);     
            }
            
             @Override
             public void removeUpdate(DocumentEvent e) {
                  
                  KhachHang khachHang = khachHang_DAO.layThongTinKhachHang(txtTimKiem.getText());
                  String colTieuDe1[] = new String[]{"Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Địa chỉ"};
                   DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);
                      Object[] row;
                       row = new Object[4];
                       row[0] = khachHang.getMaKhachHang();
                       row[1] = khachHang.getTenKhachHang();
                       row[2] = khachHang.getSoDienThoai();
                       row[3] = khachHang.getDiaChi();
                      model.addRow(row);
      jTable1.setModel(model);     
                    
                
             }
             
             @Override
             public void changedUpdate(DocumentEvent e) {
             }
         });
        }
     }
     
     private void capNhatDanhSachKhachHang(){
        khachHang_DAO = new KhachHangDAO_IMP();
        ArrayList<KhachHang> dsKhachHang = khachHang_DAO.layDanhSachKhachHang();
      
        String colTieuDe1[] = new String[]{"Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Địa chỉ"};
        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);
           Object[] row;
        for (KhachHang khachHang : dsKhachHang) {
              row = new Object[12];
            // GÁN GIÁ TRỊ
            row[0] = khachHang.getMaKhachHang();
            row[1] = khachHang.getTenKhachHang();
            row[2] = khachHang.getSoDienThoai();
            row[3] = khachHang.getDiaChi();
           model.addRow(row);
        }
        jTable1.setModel(model);
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLapHoaDon;
    private javax.swing.JButton btnSuaThongTinKhachHang;
    private javax.swing.JButton btnThemKhachHang;
    private javax.swing.JComboBox<String> cboPhuongXa;
    private javax.swing.JComboBox<String> cboQuanHuyen;
    private javax.swing.JComboBox<String> cboTinhThanhPho;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblMaKHKyTu;
    private javax.swing.JLabel lblMaKhachHang;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenKhachHang;
    private ServiceUser.TextFieldSuggestion txtTimKiem;
    private javax.swing.JLabel txtTraCuuKhachHang;
    // End of variables declaration//GEN-END:variables
}
